apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: manager-config
  files:
  - controller_manager_config.yaml

images:
- name: t2-operator
  newName: quay.io/amdaecgt2/amd-t2
  newTag: v5.3.8