apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: t2-operator
    app.kubernetes.io/part-of: t2-operator
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: t2-operator
    app.kubernetes.io/part-of: t2-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - name: manager
          image: quay.io/amdaecgt2/amd-t2:v5.3.8
          command:
            - /manager
          args:
            - "--metrics-bind-address=[::]:8084"
            -  "--health-probe-bind-address=[::]:8085"
            # - "--health-probe-bind-address=0.0.0.0:8085"
            # - "--metrics-bind-address=0.0.0.0:8084"
            - "--leader-elect"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8085
              # host: "::1"
              # host: 0.0.0.0
              # scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8085
              # host: "::1"
              # host: 0.0.0.0
              # scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 900m
              memory: 900Mi
            requests:
              cpu: 900m
              memory: 900Mi
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      imagePullSecrets:
      - name: t2-operator-quay-secret      
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: controller-manager-service
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    control-plane: controller-manager
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      name: metrics
    - protocol: TCP
      port: 8085
      targetPort: 8085
      name: health-probe
  # # ipFamilyPolicy: PreferDualStack
  # ipFamilyPolicy: SingleStack
  # ipFamilies:;
  # - IPv6
  # # - IPv4
