---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-sriovfect2-amd-com-v1-sriovt2card
  failurePolicy: Fail
  name: vsriovt2card.kb.io
  rules:
  - apiGroups:
    - sriovfect2.amd.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sriovt2cards
  sideEffects: None
