apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: t2-operator
    app.kubernetes.io/part-of: t2-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  # name: t2-operator-controller-manager
  namespace: system
# ---
# apiVersion: security.openshift.io/v1
# kind: SecurityContextConstraints
# metadata:
#   name: custom-scc
# allowHostDirVolumePlugin: true
# allowHostIPC: true
# allowHostNetwork: true
# allowHostPID: true
# allowHostPorts: true
# allowPrivilegeEscalation: true
# allowPrivilegedContainer: true
# allowedCapabilities:
# - 'ALL'
# fsGroup:
#   type: RunAsAny
# runAsUser:
#   type: RunAsAny
# seLinuxContext:
#   type: RunAsAny
# seccompProfiles:
# - '*'
# supplementalGroups:
#   type: RunAsAny
# volumes:
# - '*'
# users:
# - system:serviceaccount:system:t2-operator-controller-manager
# # - system:serviceaccount:amd-xilinx-t2:controller-manager
