# permissions for end users to edit sriovt2cards.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sriovt2card-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: t2-operator
    app.kubernetes.io/part-of: t2-operator
    app.kubernetes.io/managed-by: kustomize
  name: sriovt2card-editor-role
rules:
- apiGroups:
  - sriovfect2.amd.com
  resources:
  - sriovt2cards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sriovfect2.amd.com
  resources:
  - sriovt2cards/status
  verbs:
  - get
