apiVersion: v1
kind: Pod
metadata:
  name: bbdev-non-root-app
  namespace: amd-xilinx-t2
  labels:
    app: bbdev
spec:
  nodeSelector:
    kubernetes.io/hostname: api.teleco-t2-sn.amd.com
  securityContext:
    fsGroup: 1001
  containers:
    - name: sample-non-root-container
      image: hitendramhatre/amd-xilinx-t2-3.3id3:v1.2
      command: ["sleep", "infinity"]
      securityContext:
        privileged: false
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        runAsUser: 1001
        capabilities:
          #add: ["IPC_LOCK", "SYS_NICE"]
          add: ["DAC_READ_SEARCH", "IPC_LOCK", "SYS_NICE", "SYS_RESOURCE", "SYS_ADMIN"]
      env:
        - name: VFIO_VF_TOKEN
          value: 14d63f20-8445-11ea-8900-1f9ce7d5650d
      resources:
        limits:
          hugepages-2Mi: 1Gi
          hugepages-1Gi: 4Gi
          memory: 20Gi
          cpu: "8"
          amd.com/amd_xilinx_t2_vf: 1
        requests:
          hugepages-2Mi: 1Gi
          hugepages-1Gi: 4Gi
          memory: 20Gi
          cpu: "8"
          amd.com/amd_xilinx_t2_vf: 1
      volumeMounts:
        - mountPath: /home/nonroot/hugepages-2Mi
          name: hugepage-2mi
          readOnly: false
        - mountPath: /home/nonroot/hugepages-1Gi
          name: hugepage-1gi
          readOnly: false
        - mountPath: /tmp/dpdk
          name: varrun
          readOnly: false
  volumes:
    - name: hugepage-2mi
      emptyDir:
        medium: HugePages-2Mi
    - name: hugepage-1gi
      emptyDir:
        medium: HugePages-1Gi
    - name: varrun
      emptyDir: {}


