apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "amd-t2-resource",
                "resourcePrefix": "amd.com",
                "deviceType": "accelerator",
                "selectors": {
                    "vendors": ["10ee"],
                    "devices": ["a048"],
                    "drivers": ["vfio-pci"]
                }
            }
        ]
    }
